FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# O arquivo index.php deve existir para não dar erro 404
RUN mkdir /var/www/html -p && touch /var/www/html/index.php
